(ns fantasia.sim.core
  (:require [fantasia.sim.tick :as tick]))

(def rng tick/rng)
(def rand-int* tick/rand-int*)
(def ->agent tick/->agent)
(def initial-world tick/initial-world)
(def tick-once tick/tick-once)
(def *state tick/*state)
(def get-state tick/get-state)
(def reset-world! tick/reset-world!)
(def set-levers! tick/set-levers!)
(def place-shrine! tick/place-shrine!)
(def appoint-mouthpiece! tick/appoint-mouthpiece!)
(def tick! tick/tick!)
