(Π_STATE
  (time "2026-03-21T19:38:06Z")
  (branch "main")
  (pre_head "86b8d71")
  (dirty true)
  (checks
    (check (status passed) (command "cd backend && clojure -X:test (149 tests / 545 assertions / 0 failures / 0 errors)"))
    (check (status passed) (command "npm run build --prefix web"))
  )
  (repo_notes
    (upstream "origin/main")
    (status_digest "a8f2-e5f9-8bd2-773d")
    (note "Persist the Fork Tales canonical-path relocation across backend config, story-engine docs/specs, receipts, and the deployed web node shim file.")
    (note "Keep the currently deployed dedicated gates.ussy.promethean.rest storyteller path documented against the new orgs/octave-commons/fork_tales narrative home.")
    (note "push branch: pi/fork-tax/2026-03-21-193439")
    (note "origin remains git@github.com:octave-commons/gates-of-aker.git; current local main diverges from origin/main, so the snapshot is published on a dedicated Π branch plus tag.")
    (changed_file "\".\\316\\267\\316\\274/REPO_STATE_HASH\"")
    (changed_file "\".\\316\\267\\316\\274/registry.jsonl\"")
    (changed_file "\".\\316\\267\\316\\274/\\316\\240_LAST.md\"")
    (changed_file "\".\\316\\267\\316\\274/\\316\\240_MANIFEST.sha256\"")
    (changed_file "\".\\316\\267\\316\\274/\\316\\240_STATE.sexp\"")
    (changed_file "backend/src/fantasia/config.clj")
    (changed_file "docs/notes/fantasia/fork-tales-story-engine.md")
    (changed_file "docs/planning/spec/2026-03-20-fork-tales-story-engine.md")
    (changed_file "receipts.log")
    (changed_file "web/src/node-shims.d.ts")
  )
)
